[package]
name = "prototype_dv_repo_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown-gen = "1.2.1"
serde = { version = "1.0.194", features = ["derive"]}
serde_yaml = "0.9.30"
